import { ArrowLeft, CalendarDays, Plus } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { AppShell } from '../components/app-shell'
import { ActiveCheckBanner } from '../components/active-check-banner'
import { Button } from '../components/ui/button'
import { addOrIncrementCodeDate, getCodeDates, getProduct } from '../services/product-service'
import { activeCodeDateCheckId } from '../services/code-date-check-service'
import type { CodeDate, Product } from '../types/domain'

export function ProductDetailsPage() {
  const { productId } = useParams()
  const [product, setProduct] = useState<Product | null>(null); const [dates, setDates] = useState<CodeDate[]>([]); const [adding, setAdding] = useState(false); const [expiry, setExpiry] = useState(''); const [quantity, setQuantity] = useState('1'); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!productId) return; try { const [nextProduct, nextDates] = await Promise.all([getProduct(productId), getCodeDates(productId)]); setProduct(nextProduct); setDates(nextDates) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load product.') } }, [productId])
  useEffect(() => { void load() }, [load])
  async function save(event: React.FormEvent) { event.preventDefault(); const codeDateCheckId = activeCodeDateCheckId(); if (!productId || !codeDateCheckId) { setError('Start a Code Date Check before adding an expiration date.'); return } setSaving(true); setError(''); try { await addOrIncrementCodeDate({ productId, codeDateCheckId, expirationDate: new Date(`${expiry}T12:00:00`), quantity: Number(quantity) }); setAdding(false); setExpiry(''); setQuantity('1'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save expiration date.') } finally { setSaving(false) } }
  if (!product && !error) return <AppShell><p className="text-sm text-slate-500">Loading product…</p></AppShell>
  if (!product) return <AppShell><Link to="/scan" className="text-sm font-semibold text-brand-600">← Back to scanner</Link><p className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error || 'Product not found.'}</p></AppShell>
  return <AppShell><Link to="/scan" className="inline-flex items-center gap-1 text-sm font-semibold text-brand-600"><ArrowLeft size={16}/>Back to scanner</Link><ActiveCheckBanner/><section className="mt-5 rounded-2xl bg-white p-5 shadow-card"><div className="flex gap-4">{product.imageUrl ? <img src={product.imageUrl} alt="" className="h-24 w-24 rounded-xl object-cover"/> : <div className="grid h-24 w-24 shrink-0 place-items-center rounded-xl bg-brand-50 text-2xl">🥫</div>}<div className="min-w-0"><h2 className="text-xl font-bold">{product.name}</h2><p className="mt-2 text-sm text-slate-600">{product.description || product.name}</p><p className="mt-3 text-xs text-slate-500">UPC: {product.upc || product.barcode}{product.vendorCode ? ` · Vendor ${product.vendorCode}` : ''}{product.subDepartment ? ` · ${product.subDepartment}` : ''}</p></div></div></section><section className="mt-7"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Code dates</h3><p className="text-sm text-slate-500">Oldest expiration first</p></div><Button onClick={() => setAdding(true)}><Plus size={17} className="mr-1"/>Add expiration date</Button></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{adding && <form onSubmit={save} className="mt-4 rounded-2xl bg-brand-50 p-4"><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Expiration date<input className="mt-1 w-full rounded-xl border bg-white p-3" type="date" value={expiry} onChange={event => setExpiry(event.target.value)} required /></label><label className="text-sm font-medium">Quantity<input className="mt-1 w-full rounded-xl border bg-white p-3" type="number" min="1" value={quantity} onChange={event => setQuantity(event.target.value)} required /></label></div><div className="mt-4 flex gap-3"><Button type="button" variant="secondary" className="flex-1" onClick={() => setAdding(false)}>Cancel</Button><Button className="flex-1" disabled={saving}>{saving ? 'Saving…' : 'Save code date'}</Button></div></form>}<div className="mt-4 space-y-3">{!dates.length ? <p className="rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">No expiration dates have been added.</p> : dates.map(codeDate => <CodeDateRow key={codeDate.id} date={codeDate}/>)}</div></section></AppShell>
}
const STATUS_LABEL: Record<string, string> = { active: 'Active', marked_down: 'Marked Down', cleared: 'Cleared', removed: 'Removed' }
function CodeDateRow({ date }: { date: CodeDate }) { return <article className="flex items-center justify-between rounded-2xl bg-white p-4 shadow-card"><div><p className="flex items-center gap-2 font-bold"><CalendarDays size={17} className="text-brand-600"/>{date.expirationDate.toLocaleDateString()}</p><p className="mt-1 text-sm text-slate-500">Quantity: {date.quantity}</p>{date.status === 'marked_down' && date.recheckAt && <p className="mt-1 text-xs font-medium text-amber-700">Recheck by {date.recheckAt.toLocaleDateString()}</p>}</div><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-700">{STATUS_LABEL[date.status] ?? date.status}</span></article> }
